### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by junpet** [TheConnMan/docker-hub-rss#18]
I use this container for months, automatic updating with ouroboros without any problem. Today I played a little with traefik (using `v1`, tried to set up `v2`), and I just realized my dockerhubrss container is down. I tried to start the container and I got the following:

```
docker-hub-rss    | 2020-05-12T06:44:31.983821306Z yarn start v0.24.6
docker-hub-rss    | 2020-05-12T06:44:32.112275766Z $ node index.js 
docker-hub-rss    | 2020-05-12T06:44:32.624243495Z /app/node_modules/docker-hub-api/src/api.js:549
docker-hub-rss    | 2020-05-12T06:44:32.624348082Z                         ...details,
docker-hub-rss    | 2020-05-12T06:44:32.624364167Z                         ^^^
docker-hub-rss    | 2020-05-12T06:44:32.624376341Z 
docker-hub-rss    | 2020-05-12T06:44:32.624387770Z SyntaxError: Unexpected token ...
docker-hub-rss    | 2020-05-12T06:44:32.624399507Z     at createScript (vm.js:74:10)
docker-hub-rss    | 2020-05-12T06:44:32.624410824Z     at Object.runInThisContext (vm.js:116:10)
docker-hub-rss    | 2020-05-12T06:44:32.624422844Z     at Module._compile (module.js:533:28)
docker-hub-rss    | 2020-05-12T06:44:32.624433934Z     at Object.Module._extensions..js (module.js:580:10)
docker-hub-rss    | 2020-05-12T06:44:32.624445265Z     at Module.load (module.js:503:32)
docker-hub-rss    | 2020-05-12T06:44:32.624456178Z     at tryModuleLoad (module.js:466:12)
docker-hub-rss    | 2020-05-12T06:44:32.624467530Z     at Function.Module._load (module.js:458:3)
docker-hub-rss    | 2020-05-12T06:44:32.624478810Z     at Module.require (module.js:513:17)
docker-hub-rss    | 2020-05-12T06:44:32.624490141Z     at require (internal/module.js:11:18)
docker-hub-rss    | 2020-05-12T06:44:32.624501304Z     at Object.<anonymous> (/app/index.js:1:82)
docker-hub-rss    | 2020-05-12T06:44:32.630063891Z error Command failed with exit code 1.
```

For reference, this is my `docker-compose.yml`, nothing fancy:

```yml
version: "3.7"

services:
  docker-hub-rss:
    image: theconnman/docker-hub-rss
    container_name: docker-hub-rss
    restart: always
    networks:
      - traefik-network
    labels:
      - "com.ouroboros.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.backend=dockerhubrss"
      - "traefik.frontend.rule=Host:dockerhubrss.${DOMAINNAME}"
      - "traefik.port=3000"
      - "traefik.docker.network=traefik-network"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik-network:
    external: true
```

I tried to pull the latest image, but no new image, I use the latest.
```
REPOSITORY                  TAG                 DIGEST                                                                    IMAGE ID            CREATED             SIZE
theconnman/docker-hub-rss   latest              sha256:9c7f74d19be4c091c553ea1155475b11101b68092794a63bb80ca9a15e40fd6e   3c304cc754df        2 days ago          109MB
```
